from pathlib import Path

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import Image, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

from database.db import get_connection


ROOT = Path(__file__).resolve().parents[2]
REPORT_DIR = ROOT / "reports"


def generate_report(prediction_id):
    REPORT_DIR.mkdir(exist_ok=True)
    with get_connection() as conn:
        row = conn.execute(
            """
            SELECT predictions.*, patients.name, patients.age, patients.gender
            FROM predictions
            JOIN patients ON patients.id = predictions.patient_id
            WHERE predictions.id = ?
            """,
            (prediction_id,),
        ).fetchone()
    if row is None:
        raise ValueError("Prediction not found.")

    report_path = REPORT_DIR / f"pneumovision-report-{prediction_id}.pdf"
    doc = SimpleDocTemplate(
        str(report_path),
        pagesize=A4,
        rightMargin=40,
        leftMargin=40,
        topMargin=40,
        bottomMargin=40,
    )
    styles = getSampleStyleSheet()
    story = [
        Paragraph("PneumoVision AI Medical Report", styles["Title"]),
        Paragraph("AI-Based Pneumonia Detection System", styles["Heading2"]),
        Spacer(1, 0.18 * inch),
    ]

    rows = [
        ["Patient Name", row["name"]],
        ["Age", row["age"] or "Not provided"],
        ["Gender", row["gender"]],
        ["Prediction", row["prediction"]],
        ["Confidence", f"{row['confidence']}%"],
        ["Prediction Date", row["created_at"]],
    ]
    table = Table(rows, colWidths=[1.8 * inch, 4.6 * inch])
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#edf2f7")),
                ("TEXTCOLOR", (0, 0), (-1, -1), colors.HexColor("#1f2937")),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
                ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
                ("PADDING", (0, 0), (-1, -1), 8),
            ]
        )
    )
    story.extend([table, Spacer(1, 0.25 * inch)])

    gradcam_path = ROOT / row["gradcam_path"].lstrip("/")
    if gradcam_path.exists():
        story.append(Paragraph("Grad-CAM Visualization", styles["Heading2"]))
        story.append(Image(str(gradcam_path), width=4.8 * inch, height=3.5 * inch))
        story.append(Spacer(1, 0.2 * inch))

    story.extend(
        [
            Paragraph("Hospital Logo Placeholder", styles["Normal"]),
            Spacer(1, 0.22 * inch),
            Paragraph("Doctor Signature Placeholder", styles["Normal"]),
            Spacer(1, 0.16 * inch),
            Paragraph(
                "Disclaimer: This report is generated by an educational AI prototype and must be reviewed by a qualified medical professional.",
                styles["Italic"],
            ),
        ]
    )
    doc.build(story)
    return report_path

